name: Daily Tour Check

on:
  schedule:
    - cron: '0 5,17 * * *' # Запуск в 09:00 и 21:00 МСК
  workflow_dispatch:      # Кнопка ручного запуска

# ВАЖНО: Разрешаем роботу обновлять файлы (историю цен)
permissions:
  contents: write

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python -u main.py

      # СОХРАНЕНИЕ ИСТОРИИ ЦЕН
      - name: Commit and push history
        run: |
          git config --global user.name 'PriceBot'
          git config --global user.email 'bot@noreply.github.com'
          # Если файла еще нет, git add его добавит. Если есть - обновит.
          git add history.json
          # Если цены не изменились и коммитить нечего - не падать с ошибкой
          git commit -m "Update price history" || exit 0
          git push
